In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor 
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, BaggingClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
from collections import Counter
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving merged_multitrain_20000.csv to merged_multitrain_20000.csv


In [ ]:
df = pd.read_csv('merged_multitrain_20000.csv' )
df

tachometer  ub_axial  ub_radial   ub_tang  oh_axial  oh_radial  \
0        -0.56615 -0.001146   0.305660  0.079787   0.89718   0.042021   
1        -0.57703 -0.035375  -0.221180 -0.020031   0.85526   0.042239   
2        -0.57269 -0.907130   0.105560 -0.022671   0.82563   0.043843   
3        -0.57042  1.240900  -0.006351 -0.026974   0.89155   0.046994   
4        -0.57810 -1.706400  -0.290040 -0.084517   0.82343   0.048085   
...           ...       ...        ...       ...       ...        ...   
40001    -0.55047  0.262480   1.298100  0.251230   1.51630  -0.021968   
40002    -0.55007 -1.409300   0.487890  0.178130   1.55030  -0.020588   
40003    -0.54698 -0.843110   1.118400  0.236940   1.60820  -0.021622   
40004    -0.55191 -0.807240   0.623100  0.214800   1.64790  -0.020646   
40005    -0.54681 -2.167900   0.667650  0.233370   1.66110  -0.024574   

       oh_tang     micro  fault  
0      0.24238 -0.154910      0  
1      0.22954  0.175790      0  
2      0.24298 -0.072428      0  
3      0.34997  0.062355      0  
4      0.30320  0.054348      0  
...        ...       ...    ...  
40001 -0.44225 -0.096084      5  
40002 -0.59304  0.132840      5  
40003 -0.71696 -0.096133      5  
40004 -0.89042  0.115780      5  
40005 -1.09110  0.007352      5  

[40006 rows x 9 columns]

In [ ]:
df.shape

(40006, 9)

In [ ]:
df.fault.value_counts()

0    20001
1     4001
2     4001
3     4001
4     4001
5     4001
Name: fault, dtype: int64

In [ ]:
from imblearn.over_sampling import BorderlineSMOTE
x = df.drop('fault', axis=1)
x = x.drop('tachometer',axis = 1)
y = df['fault']

In [ ]:
SS = StandardScaler()
df_scaled = pd.DataFrame(SS.fit_transform(x), columns = x.columns)
df_scaled

ub_axial  ub_radial   ub_tang  oh_axial  oh_radial   oh_tang     micro
0      0.000853   0.591497  0.154607  0.700907   0.212091  0.171084 -1.352283
1     -0.019594  -0.433887 -0.043770  0.657686   0.212435  0.153835  1.290707
2     -0.540346   0.202045 -0.049017  0.627137   0.214964  0.171890 -0.693078
3      0.742802  -0.015767 -0.057568  0.695103   0.219933  0.315620  0.384122
4     -1.017798  -0.567908 -0.171929  0.624868   0.221653  0.252789  0.320129
...         ...        ...       ...       ...        ...       ...       ...
40001  0.158333   2.523075  0.495331  1.339242   0.111189 -0.748646 -0.882139
40002 -0.840322   0.946170  0.350053  1.374297   0.113365 -0.951217  0.947446
40003 -0.502103   2.173326  0.466931  1.433994   0.111734 -1.117691 -0.882531
40004 -0.480676   1.209328  0.422931  1.474927   0.113273 -1.350716  0.811101
40005 -1.293480   1.296036  0.459836  1.488536   0.107080 -1.620309 -0.055471

[40006 rows x 7 columns]

In [ ]:
X_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200]
}

rfclassifier = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 10, n_jobs = -1, verbose = 2)
rfclassifier.fit(X_train, y_train)# fit function is where it trains
rfclassifier.best_params_

Fitting 10 folds for each of 72 candidates, totalling 720 fits


KeyboardInterrupt: ignored

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report, average_precision_score, accuracy_score, f1_score
for i in range(10):
  X_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = None)
  grid = RandomForestClassifier(bootstrap=True,max_depth = 80, max_features = 3,min_samples_leaf= 3,min_samples_split= 8,n_estimators= 200)
  grid.fit(X_train, y_train)
  print("Train iteration",i+1)

Train iteration 1
Train iteration 2
Train iteration 3
Train iteration 4
Train iteration 5
Train iteration 6
Train iteration 7
Train iteration 8
Train iteration 9
Train iteration 10


In [ ]:
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report, average_precision_score, accuracy_score, f1_score

In [ ]:

grid_predictions = grid.predict(x_test)
  
# print classification report
print(confusion_matrix(y_test, grid_predictions))
print(classification_report(y_test, grid_predictions))


[[3804  113   66    0    0    6]
 [ 138  629    3    0    0    3]
 [ 111    5  671    2    0    0]
 [   0    0    0  796    0    0]
 [   0    0    0    0  804    8]
 [  17    0    0    6    0  820]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      3989
           1       0.84      0.81      0.83       773
           2       0.91      0.85      0.88       789
           3       0.99      1.00      0.99       796
           4       1.00      0.99      1.00       812
           5       0.98      0.97      0.98       843

    accuracy                           0.94      8002
   macro avg       0.94      0.93      0.94      8002
weighted avg       0.94      0.94      0.94      8002



In [ ]:
grid_predictions1 = grid.predict(X_train)
print("Train accuracy:",accuracy_score(y_train,grid_predictions1))
print("Train confusion matrix",confusion_matrix(y_train,grid_predictions1))

Train accuracy: 0.9887201599800025
Train confusion matrix [[15929    60    22     0     0     1]
 [  144  3073    11     0     0     0]
 [   62     3  3145     2     0     0]
 [    0     0     0  3204     0     1]
 [    2     1     0     0  3177     9]
 [   35     5     0     3     0  3115]]


**Decision Tree**

In [ ]:
#Decision Tree
param_grid = {
    'criterion' : ['gini', 'entropy'],
    'max_depth':[4,5,6,7,8,9,10,11,12,15,20,30],
    'min_samples_split' : range(10,500,20),
    'splitter' : ['best', 'random'],
    'min_samples_leaf': [5,8,11],
    'max_features': ['log2', 'sqrt','auto']
}

# Create a based model
dt = DecisionTreeClassifier()
# Instantiate the grid search model
dtClassifier = GridSearchCV(estimator = dt, param_grid = param_grid, 
                          cv = 10, n_jobs = -1, verbose = 2)

dtClassifier.fit(X_train, y_train)
dtClassifier.best_params_

best Hyperparameters for Decision tree

Fitting 10 folds for each of 10800 candidates, totalling 108000 fits
{'criterion': 'entropy',
 'max_depth': 15,
 'max_features': 'log2',
 'min_samples_leaf': 5,
 'min_samples_split': 10,
 'splitter': 'best'}

**KNN**

In [ ]:
knn = KNeighborsClassifier(algorithm = 'brute')

k_range = list(range(1, 100))
param_grid = dict(n_neighbors=k_range)

# Instantiate the grid search model
knnClassifier = GridSearchCV(estimator = knn, param_grid = param_grid, 
                          cv = 10, n_jobs = -1, verbose = 2)

knnClassifier.fit(X_train, y_train)
knnClassifier.best_params_

Fitting 10 folds for each of 99 candidates, totalling 990 fits


{'n_neighbors': 3}

In [ ]:
print('Cross-validation Score:', knnClassifier.best_score_)
print('Best Hyperparameters:', knnClassifier.best_params_)

Cross-validation Score: 0.8847642631208996
Best Hyperparameters: {'n_neighbors': 3}


In [ ]:
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report, average_precision_score, accuracy_score, f1_score
y_pred_train_binary = knnClassifier.predict(X_train)
y_pred_train_binary

array([0, 3, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report, average_precision_score, accuracy_score, f1_score
print(confusion_matrix(y_train, y_pred_train_binary))
print(classification_report(y_train, y_pred_train_binary))

[[15458   335   275     0     0     1]
 [  611  2574    26     0     0     0]
 [  438    13  2730     1     0     0]
 [    0     0     0  3193     0     0]
 [   12     0     0     1  3140    24]
 [   74    15    18    24     1  3040]]
              precision    recall  f1-score   support

           0       0.93      0.96      0.95     16069
           1       0.88      0.80      0.84      3211
           2       0.90      0.86      0.88      3182
           3       0.99      1.00      1.00      3193
           4       1.00      0.99      0.99      3177
           5       0.99      0.96      0.97      3172

    accuracy                           0.94     32004
   macro avg       0.95      0.93      0.94     32004
weighted avg       0.94      0.94      0.94     32004



**SVM**

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report, average_precision_score, accuracy_score, f1_score


param_grid = {'C': [1,10,100,1000,10000], 
              'gamma': [0.0001,0.001,0.01,0.1,1],
              'kernel': ['poly'],'degree':[3,4]} 
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
grid.fit(X_train, y_train)

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report, average_precision_score, accuracy_score, f1_score
for i in range(15):
  X_train,x_test,y_train,y_test = train_test_split(df_scaled,y, test_size = 0.2, random_state = None)
  grid2 = SVC(C= 1000,gamma= 1,kernel = 'rbf')
  grid2.fit(X_train, y_train)
  print("Train iteration",i+1)

Train iteration 1
Train iteration 2
Train iteration 3
Train iteration 4
Train iteration 5
Train iteration 6
Train iteration 7
Train iteration 8
Train iteration 9
Train iteration 10
Train iteration 11
Train iteration 12
Train iteration 13
Train iteration 14
Train iteration 15


In [ ]:

grid_predictions2 = grid2.predict(x_test)
  
# print classification report
print(confusion_matrix(y_test, grid_predictions2))
print(classification_report(y_test, grid_predictions2))
print("Train accuracy:",accuracy_score(y_train,grid2.predict(X_train)))
print("Test accuracy:", accuracy_score(y_test,grid_predictions2))

[[3739  128  113    0    0    1]
 [ 182  599    9    0    0    0]
 [ 141    5  687    0    0    0]
 [   0    0    0  812    0    3]
 [   1    0    0    0  759    4]
 [  11    4    1    3    2  798]]
              precision    recall  f1-score   support

           0       0.92      0.94      0.93      3981
           1       0.81      0.76      0.79       790
           2       0.85      0.82      0.84       833
           3       1.00      1.00      1.00       815
           4       1.00      0.99      1.00       764
           5       0.99      0.97      0.98       819

    accuracy                           0.92      8002
   macro avg       0.93      0.91      0.92      8002
weighted avg       0.92      0.92      0.92      8002

Train accuracy: 0.9637857767779028
Test accuracy: 0.9240189952511872


In [ ]:
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report, average_precision_score, accuracy_score, f1_score
y_pred_train = grid2.predict(X_train)
y_pred_train
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report, average_precision_score, accuracy_score, f1_score

print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

[[15543   245   232     0     0     0]
 [  379  2825     7     0     0     0]
 [  289     7  2872     0     0     0]
 [    0     0     0  3186     0     0]
 [    0     0     0     0  3237     0]
 [    0     0     0     0     0  3182]]
              precision    recall  f1-score   support

           0       0.96      0.97      0.96     16020
           1       0.92      0.88      0.90      3211
           2       0.92      0.91      0.91      3168
           3       1.00      1.00      1.00      3186
           4       1.00      1.00      1.00      3237
           5       1.00      1.00      1.00      3182

    accuracy                           0.96     32004
   macro avg       0.97      0.96      0.96     32004
weighted avg       0.96      0.96      0.96     32004



In [ ]:
import pickle

with open('motor_fault_rfmodel','wb') as f:
  pickle.dump(grid,f)

In [ ]:
import pickle

with open('motor_fault_rfmodel','rb') as f:
  mod=pickle.load(f)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving merged_20000_test.csv to merged_20000_test (1).csv


In [ ]:
test_data = pd.read_csv('/content/merged_20000_test.csv' )
test_data

tachometer  ub_axial  ub_radial   ub_tang  oh_axial  oh_radial   oh_tang  \
0      -0.46507   0.32260   0.406940  0.064681   0.32869  -0.012733  0.094531   
1      -0.53586  -0.11591  -0.271120  0.009039   0.30377  -0.009884  0.075387   
2      -0.54062  -1.03650   0.166220  0.024178   0.30780  -0.012759  0.088468   
3      -0.45362   0.95139   0.038656  0.020016   0.33036   0.001051  0.135510   
4      -0.58190  -1.57460  -0.248520 -0.026415   0.26675   0.007963  0.075637   
..          ...       ...        ...       ...       ...        ...       ...   
301    -0.54217  -0.57947   0.068483 -0.535510   2.89360   0.188770  0.634920   
302    -0.55392  -1.99280  -0.351690 -0.588370   2.85250   0.182580  0.653200   
303    -0.54053  -1.03640   0.255390 -0.540750   2.83160   0.181410  0.677930   
304    -0.55126  -1.28580   0.128820 -0.540440   2.79050   0.179690  0.643620   
305    -0.54761  -1.74840   0.383450 -0.498250   2.74220   0.175700  0.603370   

        micro  fault  
0   -0.128360      0  
1    0.133540      0  
2   -0.106990      0  
3    0.079221      0  
4    0.047168      0  
..        ...    ...  
301 -0.081822      5  
302  0.111200      5  
303 -0.091947      5  
304  0.111320      5  
305  0.001608      5  

[306 rows x 9 columns]

In [ ]:
test_data.fault.value_counts()

0    51
1    51
2    51
3    51
4    51
5    51
Name: fault, dtype: int64

In [ ]:
x1 = test_data.drop('fault', axis=1)
x1 = x1.drop('tachometer',axis = 1)
y1 = test_data['fault']

In [ ]:
SS = StandardScaler()
test_scaled = pd.DataFrame(SS.fit_transform(x1), columns = x1.columns)

In [ ]:
test_pred=grid.predict(x1)

In [ ]:
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report, average_precision_score, accuracy_score, f1_score

print(confusion_matrix(y1, test_pred))
print(classification_report(y1, test_pred))

[[50  1  0  0  0  0]
 [20 24  0  0  1  6]
 [ 0  0 51  0  0  0]
 [ 0  0  0 51  0  0]
 [ 0  0  0  0 51  0]
 [ 0  0  0  0  0 51]]
              precision    recall  f1-score   support

           0       0.71      0.98      0.83        51
           1       0.96      0.47      0.63        51
           2       1.00      1.00      1.00        51
           3       1.00      1.00      1.00        51
           4       0.98      1.00      0.99        51
           5       0.89      1.00      0.94        51

    accuracy                           0.91       306
   macro avg       0.92      0.91      0.90       306
weighted avg       0.92      0.91      0.90       306

